### ISSUE TITLE
REPL doesn't seem to work w/ v0.3.0

### ISSUE THREAD

**Issue by mlliarm** [melvic-ybanez/chi#80]
Hello,

Awesome project ! I'm really interested in Scala and the Curry-Howard isomorphism, so I thought that this project is really nice.

While 

```bash
java -jar chi-0.3.0.jar
```
works pretty well, the `java -jar chi-0.3.0.jar repl` doesn't start the REPL. I get no error messages either.

Not sure what I might be doing wrong.

Please see attached image for the JVM I'm running.

Let me know if you need any extra info. Thanks !

![2022-04-19-032258_1920x1080_scrot](https://user-images.githubusercontent.com/5833270/163901741-3ca0e89a-05cc-426a-ad39-01719f153773.png)

**Comment by melvic-ybanez** [comment]
Thanks for the report. I will look into it.
