### ISSUE TITLE
Build with sbt failure

### ISSUE THREAD

**Issue by mlliarm** [melvic-ybanez/chi#82]
Hello,

Thanks for the fast response regarding #80 !

I tried building chi from source to create the new `jar` that will have the updated fixes, but `sbt run` fails for me. I run the command from within the `chi` directory, which I cloned from this repo.

Should I use a different Java or sbt version? Or it's maybe something path-related?

It'd be great if you could add some additional steps in the `README.md` on how to build the jar or the `class` files from source when you have the time, for beginners like me :$.

Or if you want, you could post in a comment here the steps required to build successfully from source and I will send a PR with that information typed in the `README.md` for you :).

Attaching the error logs I got: [chi_compilation_with_sbt_error_logs2.txt](https://github.com/melvic-ybanez/chi/files/8513232/chi_compilation_with_sbt_error_logs2.txt).

Best regards.

**Comment by melvic-ybanez** [comment]
I'm also having issues running it with `sbt run` command. However my error is related to the RSyntaxTextArea library (can't find the bundle for it). For the mean time, have you tried the `sbt assembly` command instead? That command is how I generate the fat jar.

**Comment by melvic-ybanez** [comment]
Hmm. I couldn't replicate the issue you mentioned. I'm using OpenJDK 17:

```
openjdk version "17.0.2" 2022-01-18 LTS
OpenJDK Runtime Environment Zulu17.32+13-CA (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.32+13-CA (build 17.0.2+8-LTS, mixed mode, sharing)
```

**Comment by mlliarm** [comment]
I've just installed `openjdk-17-jdk`. 

I had only installed `openjdk-17-jre` and it seems that sbt was using `javac-11`, as far as I can guess.

Retrying with `sbt assembly` and will update asap.

**Comment by mlliarm** [comment]
Still getting the following error:

```
sbt assembly
[info] welcome to sbt 1.6.2 (Debian Java 17.0.2)
[info] loading settings for project chi-build from plugins.sbt ...
[info] loading project definition from /home/milia/Documents/dev/scala/chi/project
[info] compiling 1 Scala source to /home/milia/Documents/dev/scala/chi/project/target/scala-2.12/sbt-1.0/classes ...
/home/milia/Documents/dev/scala/chi/build.sbt:7: warning: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
assemblyJarName in assembly := "chi-0.4.0-snapshot.jar"
                ^
/home/milia/Documents/dev/scala/chi/build.sbt:16: warning: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
assemblyMergeStrategy in assembly := {
```

I think the `built.sbt` has to be changed to modern standards (according to the [sbt-assembly docs](https://github.com/sbt/sbt-assembly/#applying-the-plugin-to-multi-project-buildsbt) and the [sbt docs](https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#Migrating+to+slash+syntax)) to:

```
lazy val root = (project in file("."))
  .settings(
    assembly / assemblyJarName := "chi-0.4.0-snapshot.jar",
    name := "chi",
    libraryDependencies ++= dependencies
  )
```

If this compiles, I'll send a PR. Thanks !

**Comment by mlliarm** [comment]
So it seems that the above was only a warning (or INFO level log)...It didn't affect the compilation process.

Still getting the same compilation ERRORs. Attaching logs: [chi_compilation_with_sbt_assembly_error_logs2.txt](https://github.com/melvic-ybanez/chi/files/8514163/chi_compilation_with_sbt_assembly_error_logs2.txt).

Current JDK, JRE and sbt I'm using:

```sh
$ java --version
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.2+8-Debian-1deb11u1, mixed mode, sharing)

$ javac --version
javac 17.0.2

$ sbt -version
sbt version in this project: 1.6.2
sbt script version: 1.6.2
```
Thanks for your time and for all the help !

**Comment by melvic-ybanez** [comment]
Hi. I wasn't able to get back to you earlier. Did you manage to run it on your local?

**Comment by mlliarm** [comment]
Hello @melvic-ybanez !

No, not really. Compiling both with `sbt assembly` or `sbt run` still fails with logs mentioned in [the previous comment](https://github.com/melvic-ybanez/chi/issues/82#issuecomment-1102765937)... :-/

**Comment by melvic-ybanez** [comment]
I think I might have figured out the issue. Looks like the out directory is in gitignore. I just realized it's never actually pushed.

**Comment by melvic-ybanez** [comment]
@mlliarm can you try again now?

**Comment by mlliarm** [comment]
> @mlliarm can you try again now?

Hey @melvic-ybanez , thanks !

I'll check it out tomorrow when I'll have access to a screen to plug in my RPi, 'cos I was traveling today across countries :). Thanks for your help, I'll let you know how it went asap ! Gn!

**Comment by mlliarm** [comment]
Hey @melvic-ybanez,

I've just built the latest version (`0.5.0-SNAPSHOT`) with `sbt assembly` and it compiled without any errors:

```bash
[info] Run completed in 3 seconds, 501 milliseconds.
[info] Total number of tests run: 48
[info] Suites: completed 5, aborted 0
[info] Tests: succeeded 48, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Strategy 'discard' was applied to 15 files (Run the task at debug level to see details)
[info] Strategy 'first' was applied to 3 files (Run the task at debug level to see details)
[warn] Ignored unknown package option FixedTimestamp(Some(1262304000000))
[success] Total time: 114 s (01:54), completed Apr 21, 2022, 9:18:46 PM
```

It had some warnings, but no errors at all. 

Also I ran the examples from the README.md in the REPL and they give the expected results. So all good. 

For this reason I'll close this bug as it was fixed.

Thanks a lots and keep up the good work !!! It's an amazing project even for Scala beginners like me.
